[project]
name = "resx"
version = "0.1.0"
description = "RES Explorer: VDT files postprocessing"
authors = [
    { name = "Lucas Desport", email = "lucas.desport@minesparis.psl.eu" },
    { name = "Damien Corral", email = "damien.corral@minesparis.psl.eu" },
    { name = "Jean-Paul Marmorat", email = "jean-paul.marmorat@minesparis.psl.eu" },
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2",
    "click>=8.1",
    "networkx>=3.3",
    "gravis>=0.1",
    "setuptools<80",
]

[project.scripts]
resx  = "resx.console:cli"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["resx"]
